# Generated by Django 3.1.7 on 2021-04-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplopyeedetails',
            name='mobile_number',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
