# Generated by Django 3.1.7 on 2021-04-09 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0003_auto_20210406_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='emplopyeedetails',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='emplopyeedetails',
            name='aadhar_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emplopyeedetails',
            name='pan_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emplopyeedetails',
            name='department_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loginanddashboard.department'),
        ),
    ]
