# Generated by Django 3.1.7 on 2021-04-09 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0007_auto_20210409_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_type', models.CharField(max_length=100)),
                ('a_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(max_length=100)),
                ('d_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=100)),
                ('super_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_month', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='emplopyeedetails',
            name='aadhar_copy',
            field=models.FileField(null=True, upload_to='aadhars'),
        ),
        migrations.AddField(
            model_name='emplopyeedetails',
            name='pan_copy',
            field=models.FileField(null=True, upload_to='pans'),
        ),
        migrations.CreateModel(
            name='Resignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('resign_reason', models.TextField(max_length=500)),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resign', to='loginanddashboard.emplopyeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_d', to='loginanddashboard.payroll')),
            ],
        ),
        migrations.AddField(
            model_name='payroll',
            name='employee_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll', to='loginanddashboard.emplopyeedetails'),
        ),
        migrations.CreateModel(
            name='EmployeeLeaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplayee_name', models.CharField(max_length=100)),
                ('leave_day_type', models.CharField(max_length=10)),
                ('leave_type', models.CharField(max_length=2)),
                ('leave_reason', models.TextField(max_length=500)),
                ('reject_reason', models.TextField(max_length=500)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='loginanddashboard.emplopyeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='loginanddashboard.emplopyeedetails')),
            ],
        ),
        migrations.AddField(
            model_name='emplopyeedetails',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designation', to='loginanddashboard.designation'),
        ),
        migrations.AlterField(
            model_name='emplopyeedetails',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super', to='loginanddashboard.designation'),
        ),
    ]
