# Generated by Django 3.1.7 on 2021-04-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0008_auto_20210409_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplopyeedetails',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
