# Generated by Django 3.1.7 on 2021-04-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0009_auto_20210409_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplopyeedetails',
            name='date_of_birth',
            field=models.DateField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='emplopyeedetails',
            name='mobile_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
