# Generated by Django 3.1.7 on 2021-04-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0013_auto_20210411_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowances',
            name='a_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deductions',
            name='d_amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
