# Generated by Django 3.1.7 on 2021-04-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0014_auto_20210411_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='balance_leaves',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payroll_year',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='present_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='work_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payrolldetails',
            name='bonus',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='payrolldetails',
            name='net_salary',
            field=models.FloatField(null=True),
        ),
    ]
