# Generated by Django 3.1.7 on 2021-04-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0015_auto_20210411_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowancesDeductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_type', models.CharField(max_length=100)),
                ('a_description', models.CharField(max_length=200)),
                ('a_amount', models.BigIntegerField(null=True)),
                ('deduction_type', models.CharField(max_length=100)),
                ('d_description', models.CharField(max_length=200)),
                ('d_amount', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Allowances',
        ),
        migrations.DeleteModel(
            name='Deductions',
        ),
        migrations.AddField(
            model_name='payroll',
            name='bonus',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='net_salary',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='PayrollDetails',
        ),
    ]
