# Generated by Django 3.1.7 on 2021-04-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0016_auto_20210411_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='P_T',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='basic_salary',
            field=models.BigIntegerField(null=True),
        ),
    ]
