# Generated by Django 3.1.7 on 2021-04-12 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0017_auto_20210412_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowancesdeductions',
            name='a_description',
        ),
        migrations.RemoveField(
            model_name='allowancesdeductions',
            name='d_description',
        ),
    ]
