# Generated by Django 3.1.7 on 2021-04-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0018_auto_20210412_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowancesdeductions',
            name='a_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allowancesdeductions',
            name='d_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
