# Generated by Django 3.1.7 on 2021-04-12 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0019_auto_20210412_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowancesdeductions',
            name='allowance_type',
        ),
        migrations.RemoveField(
            model_name='allowancesdeductions',
            name='deduction_type',
        ),
    ]
