# Generated by Django 3.1.7 on 2021-04-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0020_auto_20210412_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_type', models.CharField(max_length=100)),
                ('a_amount', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(max_length=100)),
                ('d_amount', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AllowancesDeductions',
        ),
    ]
