# Generated by Django 3.1.7 on 2021-04-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0021_auto_20210412_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowances',
            name='a_amount',
        ),
        migrations.RemoveField(
            model_name='allowances',
            name='allowance_type',
        ),
        migrations.RemoveField(
            model_name='deductions',
            name='d_amount',
        ),
        migrations.RemoveField(
            model_name='deductions',
            name='deduction_type',
        ),
        migrations.AddField(
            model_name='allowances',
            name='CONVEYANCE',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='allowances',
            name='FBP',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='allowances',
            name='HRA',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='allowances',
            name='Incentives',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='allowances',
            name='LTA',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deductions',
            name='PF',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deductions',
            name='TDS',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deductions',
            name='advance',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deductions',
            name='salary_Adv',
            field=models.BigIntegerField(null=True),
        ),
    ]
