# Generated by Django 3.1.7 on 2021-04-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0024_auto_20210413_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='balance_leaves',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='present_days',
        ),
        migrations.AddField(
            model_name='payroll',
            name='CONVEYANCE',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='FBP',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='HRA',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='Incentives',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='LTA',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='PF',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='TDS',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='advance',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='salary_Adv',
            field=models.BigIntegerField(null=True),
        ),
    ]
