# Generated by Django 3.1.7 on 2021-04-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0026_auto_20210413_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='gross_salary',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_deductions',
            field=models.FloatField(default=0, null=True),
        ),
    ]
