# Generated by Django 3.1.7 on 2021-04-14 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0027_auto_20210414_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='employee_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emp_pk', to='loginanddashboard.emplopyeedetails'),
        ),
    ]
