# Generated by Django 3.1.7 on 2021-04-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0028_auto_20210414_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeattendance',
            old_name='employee_id',
            new_name='employee_ida',
        ),
        migrations.RenameField(
            model_name='employeeleaves',
            old_name='employee_id',
            new_name='employee_idl',
        ),
        migrations.RenameField(
            model_name='resignation',
            old_name='employee_id',
            new_name='employee_idr',
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='days_present',
            field=models.IntegerField(null=True),
        ),
    ]
