# Generated by Django 3.1.7 on 2021-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0029_auto_20210414_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='basic_salary',
        ),
        migrations.AddField(
            model_name='emplopyeedetails',
            name='bank_acc_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
