# Generated by Django 3.1.7 on 2021-04-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0030_auto_20210414_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplopyeedetails',
            name='P_T',
        ),
        migrations.AddField(
            model_name='emplopyeedetails',
            name='bank_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='days_present',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
