# Generated by Django 3.1.7 on 2021-04-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0036_hrdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HRDetails',
        ),
    ]
