# Generated by Django 3.1.7 on 2021-04-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0037_delete_hrdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplopyeedetails',
            name='tax_saving_declarations_and_proofs',
            field=models.FileField(null=True, upload_to='tax_uploads'),
        ),
    ]
