# Generated by Django 3.1.7 on 2021-04-25 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0038_emplopyeedetails_tax_saving_declarations_and_proofs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleaves',
            name='employee_idl',
        ),
        migrations.RemoveField(
            model_name='resignation',
            name='employee_idr',
        ),
    ]
