# Generated by Django 3.1.7 on 2021-04-25 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginanddashboard', '0039_auto_20210425_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleaves',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='resignation',
            name='response',
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(null=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
