# Generated by Django 3.1.7 on 2021-04-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0040_auto_20210425_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
