# Generated by Django 3.1.7 on 2021-04-25 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0041_messages_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='user',
        ),
        migrations.AddField(
            model_name='messages',
            name='employee_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='loginanddashboard.emplopyeedetails'),
        ),
    ]
