# Generated by Django 3.1.7 on 2021-04-25 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginanddashboard', '0042_auto_20210425_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='messages',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
