# Generated by Django 3.1.7 on 2021-05-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0045_auto_20210425_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_pk', to='loginanddashboard.emplopyeedetails'),
        ),
    ]
