# Generated by Django 3.1.7 on 2021-05-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0046_auto_20210504_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='super_id',
        ),
    ]
