# Generated by Django 3.1.7 on 2021-05-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0047_remove_designation_super_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='date_cretaed',
            field=models.DateField(auto_now=True),
        ),
    ]
