# Generated by Django 3.1.7 on 2021-05-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0048_payroll_date_cretaed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplopyeedetails',
            name='date_created',
            field=models.DateField(auto_created=True),
        ),
    ]
