# Generated by Django 3.1.7 on 2021-05-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0050_emplopyeedetails_date_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='CONVEYANCE',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='FBP',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='HRA',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='Incentives',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='LTA',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='PF',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='P_T',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='TDS',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='advance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='basic_salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='salary_Adv',
            field=models.FloatField(null=True),
        ),
    ]
