# Generated by Django 3.1.7 on 2021-05-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginanddashboard', '0051_auto_20210509_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='pdfs',
            field=models.FileField(null=True, upload_to='payslip_pdfs'),
        ),
    ]
